### ISSUE TITLE
Embed metabase map from tax benefits team

### ISSUE THREAD

**Issue by CodefortheCarolinas** [CodefortheCarolinas/tax-benefit-website#17]
When the metabase map is provided by the tax benefits team, embed it in place of the map graphic.

**Comment by annelisegrimm** [comment]
Here is the iframe code from the CfA team (not actually metabase, but same idea)

<iframe title="" aria-label="Map" id="datawrapper-chart-wyMsS" src="https://datawrapper.dwcdn.net/wyMsS/1/" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="432"></iframe><script type="text/javascript">!function(){"use strict";window.addEventListener("message",(function(e){if(void 0!==e.data["datawrapper-height"]){var t=document.querySelectorAll("iframe");for(var a in e.data["datawrapper-height"])for(var r=0;r<t.length;r++){if(t[r].contentWindow===e.source)t[r].style.height=e.data["datawrapper-height"][a]+"px"}}}))}();</script>

**Comment by annelisegrimm** [comment]
Looks like this issue is already documented and this can be deleted?
