### ISSUE TITLE
Update text in orange stripe / sample messages section

### ISSUE THREAD

**Issue by CodefortheCarolinas** [CodefortheCarolinas/tax-benefit-website#19]
Add at beginning of paragraph: Agencies email, text, or call clients or members.  We recommend sending a series of messages, rather than just one.

Delete lorem ipsum text. 

Final text in this section should read: 

Agencies email, text, or call clients or members.  We recommend sending a series of messages, rather than just one. You are free to use and adapt these sample messages published with a [CC0 Public Domain Dedication](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by ewmcelvaney** [comment]
I'm going to work on this.
