### ISSUE TITLE
Update text in first white stripe (outreach partnership guide)

### ISSUE THREAD

**Issue by CodefortheCarolinas** [CodefortheCarolinas/tax-benefit-website#20]
Add at start of paragraph: Government agencies and membership organizations can conduct outreach to encourage families to claim the Child Tax Credit. 

Delete lorem ipsum text:

Final text should read: Government agencies and membership organizations can conduct outreach to encourage families to claim the Child Tax Credit. Information on how outreach partners can get involved is available in our [2022 Outreach Partnership guide.](https://codeforamerica.org/wp-content/uploads/2022/02/2022-getyourrefund-outreach-partnerships-guide-code-for-america.pdf)

**Comment by ewmcelvaney** [comment]
**Changes order of the sentences under the map** #24
