### ISSUE TITLE
Add text to white stripe above map

### ISSUE THREAD

**Issue by CodefortheCarolinas** [CodefortheCarolinas/tax-benefit-website#33]
Change title from: Get Your Child Tax Credit 
to: Help Families Get Their Child Tax Credit

also,

Add this text below the existing text in the white stripe above the map:

At Code for America, we believe that all families deserve access to free, trustworthy services to help them prepare their taxes and access the tax benefits that belong to them, such as the Child Tax Credit, and economic stimulus payments. We created [GetYourRefund.org](https://codeforamerica.org/programs/tax-benefits/getyourrefund/) and [GetCTC.org](https://codeforamerica.org/news/filing-taxes-can-get-families-thousands-of-dollars-in-flexible-cash/) to make the filing process simple, straightforward, and mobile accessible in English and Spanish.

**Comment by annelisegrimm** [comment]
Also change title from "Get Your Child Tax Credit" to 

Help Families Get Their Child Tax Credit
